### ISSUE TITLE
Some input

### ISSUE THREAD

**Issue by bstaletic** [Avi-D-coder/lsp-range-unit-survey#2]
Our client is missing from the list. [ycmd](/Valloric/ycmd) uses UTF-16, like the standard specifies.

JDT.LS and clagd use UTF-16. RLS uses UTF-8.

**Comment by bstaletic** [comment]
Ycmd: https://github.com/Valloric/ycmd/pull/857
RLS: https://github.com/rust-lang/rls/issues/1113
Clangd: https://github.com/clangd/clangd/issues/3

For jdt.ls I can't find a relevant link, so I might have been wrong.

**Comment by Avi-D-coder** [comment]
@bstaletic Thanks.
Do you want to add ycmd to https://github.com/langserver/langserver.github.io or should I?

**Comment by bstaletic** [comment]
I will post a PR to https://github.com/langserver/langserver.github.io
